### ISSUE TITLE
Wow what a stealer

### ISSUE THREAD

**Issue by BluecraftDev** [Lernox-Dev/Caramel-Hosting#10]
Hey Lernox-Dev,

I want inform you guy that the source code that you guy are made repo is my source code i have some proof that i can show that this code is mine

<img width="789" alt="image" src="https://user-images.githubusercontent.com/91048594/175776039-417eb29d-aeab-4dc3-89a0-57658637c6c0.png">

**Comment by KiaraSenpai** [comment]
Make .env file bro so no one can steal your token
if you using replit go to the 🔒 Logo then fill that
The config.json just example 😂

**Comment by KiaraSenpai** [comment]
sure? show your code then if its you make it
me and caramelo take it from Guitar Host
i guess  the developer who make this uptime
Show me your code here Sae#0029

**Comment by CarameloSz** [comment]
And from your screenshot is your token is logged in somewhere its mean you or your friend using bot source code that logged your token xD

**Comment by BluecraftDev** [comment]
i have a alot of proof

**Comment by KiaraSenpai** [comment]
sure bro? come dm me on discord
Sae#0029
